name: TimescaleDB
version: 5.2.0
slug: timescaledb
description: An open-source database built on PostgreSQL for analyzing time-series
  data with the power and convenience of SQL
url: https://github.com/expaso/hassos-addon-timescaledb
codenotary: hans@expaso.nl
arch:
- armhf
- aarch64
- amd64
- armv7
- i386
startup: system
init: false
tmpfs: true
map:
- share:rw
- backup:rw
- media:rw
timeout: 60
ports:
  5432/tcp: null
ports_description:
  5432/tcp: PostgreSQL Port. Beware! This port may already be in use. Choose another
    port-number if the add-on won't start.
options:
  databases:
  - homeassistant
  timescale_enabled:
  - homeassistant
  timescaledb:
    telemetry: basic
    maxmemory: 512MB
    maxcpus: 4
  max_connections: 50
  system_packages: []
  init_commands: []
  retry_upgrade: false
schema:
  databases:
  - str
  timescale_enabled:
  - str
  timescaledb:
    telemetry: list(off|basic)
    maxmemory: str?
    maxcpus: int(1,)?
  max_connections: int(20,)
  system_packages:
  - str
  init_commands:
  - str
  retry_upgrade: bool?
image: ghcr.io/expaso/timescaledb/{arch}
